# Generated by Django 4.1.3 on 2022-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='rwf', max_length=50, unique=True),
        ),
    ]
