# Generated by Django 4.1.3 on 2022-12-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auction_remove_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='Item',
        ),
    ]
