# Generated by Django 4.1.3 on 2022-12-09 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_auction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_ends',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
