# Generated by Django 4.1.3 on 2022-12-09 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_item_date_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_ends',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
