# Generated by Django 4.1.3 on 2022-12-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='QuestionAnswer',
        ),
    ]
