# Generated by Django 4.1.2 on 2022-12-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_bid_item_number_of_bids_delete_profile_bid_item_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
