# Generated by Django 4.1.4 on 2022-12-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
